### ISSUE TITLE
java

### ISSUE THREAD

**Issue by Sejin-999** [Sejin-999/blog-test#3]
![1](https://github.com/Sejin-999/blog-test/assets/76008226/bc2da799-a241-4c78-837b-38fc06972a12)
![1](https://github.com/Sejin-999/blog-test/assets/76008226/57ae3392-fbc1-46ad-ae3c-a9ffdd6cb958)
![2](https://github.com/Sejin-999/blog-test/assets/76008226/902999ae-658f-42ec-ba62-197c969d52e3)

**Comment by Koenisegg484** [comment]
Hi Sejin, Shivam here
I was looking for open source projects and found your issue
So what is the issue exactly ?

**Comment by Sejin-999** [comment]
just upload picture!

**Comment by Koenisegg484** [comment]
Nice, though I still don't get much. Keep it up
Wanna connect on linkedin ?
here is mine 
https://www.linkedin.com/in/shivam-chouhan-b998211b6/
